transformation_kwargs:
  add_abstract:
    - True
  add_title:
    - True
  abstract_length:
    - 200
  log_transform:
    - True
retrieval_kwargs:
  k:
    - 23
model_kwargs:
  model_name:
    - triplet
    - infonce
    - paraphrase-TinyBERT-L6-v2
  multi_process:
    - False
model_type:
  - sentencebert